from typing import Dict, Any
from github.Repository import Repository as GithubRepository

def get_repo_metadata(repo: GithubRepository) -> Dict[str, Any]:
    """
    Extracts metadata from a GitHub repository object.

    Args:
        repo: The GitHub repository object.

    Returns:
        A dictionary containing the repository's metadata.
    """
    return {
        "id": repo.id,
        "node_id": repo.node_id,
        "name": repo.name,
        "full_name": repo.full_name,
        "private": repo.private,
        "owner": repo.owner.login,
        "html_url": repo.html_url,
        "description": repo.description,
        "fork": repo.fork,
        "url": repo.url,
        "forks_url": repo.forks_url,
        "keys_url": repo.keys_url,
        "collaborators_url": repo.collaborators_url,
        "teams_url": repo.teams_url,
        "hooks_url": repo.hooks_url,
        "issue_events_url": repo.issue_events_url,
        "events_url": repo.events_url,
        "assignees_url": repo.assignees_url,
        "branches_url": repo.branches_url,
        "tags_url": repo.tags_url,
        "blobs_url": repo.blobs_url,
        "git_tags_url": repo.git_tags_url,
        "git_refs_url": repo.git_refs_url,
        "trees_url": repo.trees_url,
        "statuses_url": repo.statuses_url,
        "languages_url": repo.languages_url,
        "stargazers_url": repo.stargazers_url,
        "contributors_url": repo.contributors_url,
        "subscribers_url": repo.subscribers_url,
        "subscription_url": repo.subscription_url,
        "commits_url": repo.commits_url,
        "git_commits_url": repo.git_commits_url,
        "comments_url": repo.comments_url,
        "issue_comment_url": repo.issue_comment_url,
        "contents_url": repo.contents_url,
        "compare_url": repo.compare_url,
        "merges_url": repo.merges_url,
        "archive_url": repo.archive_url,
        "downloads_url": repo.downloads_url,
        "issues_url": repo.issues_url,
        "pulls_url": repo.pulls_url,
        "milestones_url": repo.milestones_url,
        "notifications_url": repo.notifications_url,
        "labels_url": repo.labels_url,
        "releases_url": repo.releases_url,
        "deployments_url": repo.deployments_url,
        "created_at": repo.created_at.isoformat(),
        "updated_at": repo.updated_at.isoformat(),
        "pushed_at": repo.pushed_at.isoformat(),
        "git_url": repo.git_url,
        "ssh_url": repo.ssh_url,
        "clone_url": repo.clone_url,
        "svn_url": repo.svn_url,
        "homepage": repo.homepage,
        "size": repo.size,
        "stargazers_count": repo.stargazers_count,
        "watchers_count": repo.watchers_count,
        "language": repo.language,
        "has_issues": repo.has_issues,
        "has_projects": repo.has_projects,
        "has_downloads": repo.has_downloads,
        "has_wiki": repo.has_wiki,
        "has_pages": repo.has_pages,
        "has_discussions": repo.has_discussions,
        "forks_count": repo.forks_count,
        "mirror_url": repo.mirror_url,
        "archived": repo.archived,
        "disabled": repo.disabled,
        "open_issues_count": repo.open_issues_count,
        "license": repo.license.name if repo.license else None,
        "allow_forking": repo.allow_forking,
        "is_template": repo.is_template,
        "web_commit_signoff_required": repo.web_commit_signoff_required,
        "topics": repo.get_topics(),
        "visibility": repo.visibility,
        "forks": repo.forks,
        "open_issues": repo.open_issues,
        "watchers": repo.watchers,
        "default_branch": repo.default_branch,
        "temp_clone_token": repo.temp_clone_token,
        "network_count": repo.network_count,
        "subscribers_count": repo.subscribers_count
    }
