/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for a Github repository
 */
export interface GithubRepo {
  /**
   * Global ID of the repository
   */
  github_id: number;
  /**
   * The GraphQL node ID of the repository
   */
  node_id: string;
  /**
   * The name of the repository
   */
  name: string;
  /**
   * The repository owner with repo name (e.g., owner/repo)
   */
  full_name: string;
  /**
   * The login of the owner of the repository (username or organization)
   */
  owner: string;
  /**
   * A short description of the repository
   */
  description?: string | null;
  /**
   * Whether the repository is a fork
   */
  is_fork: boolean;
  /**
   * The API URL of the repository
   */
  url: string;
  /**
   * The API URL of the repository's forks
   */
  forks_url: string;
  /**
   * The API URL of the repository's keys
   */
  keys_url: string;
  /**
   * The API URL of the repository's collaborators
   */
  collaborators_url: string;
  /**
   * The API URL of the repository's teams
   */
  teams_url: string;
  /**
   * The API URL of the repository's hooks
   */
  hooks_url: string;
  /**
   * The API URL of the repository's issue events
   */
  issue_events_url: string;
  /**
   * The API URL of the repository's events
   */
  events_url: string;
  /**
   * The API URL of the repository's assignees
   */
  assignees_url: string;
  /**
   * The API URL of the repository's branches
   */
  branches_url: string;
  /**
   * The API URL of the repository's tags
   */
  tags_url: string;
  /**
   * The API URL of the repository's blobs
   */
  blobs_url: string;
  /**
   * The API URL of the repository's git tags
   */
  git_tags_url: string;
  /**
   * The API URL of the repository's git refs
   */
  git_refs_url: string;
  /**
   * The API URL of the repository's trees
   */
  trees_url: string;
  /**
   * The API URL of the repository's statuses
   */
  statuses_url: string;
  /**
   * The API URL of the repository's languages
   */
  languages_url: string;
  /**
   * The API URL of the repository's stargazers
   */
  stargazers_url: string;
  /**
   * The API URL of the repository's contributors
   */
  contributors_url: string;
  /**
   * The API URL of the repository's subscribers
   */
  subscribers_url: string;
  /**
   * The API URL of the repository's subscription
   */
  subscription_url: string;
  /**
   * The API URL of the repository's commits
   */
  commits_url: string;
  /**
   * The API URL of the repository's git commits
   */
  git_commits_url: string;
  /**
   * The API URL of the repository's comments
   */
  comments_url: string;
  /**
   * The API URL of the repository's issue comments
   */
  issue_comment_url: string;
  /**
   * The API URL of the repository's contents
   */
  contents_url: string;
  /**
   * The API URL of the repository's compare
   */
  compare_url: string;
  /**
   * The API URL of the repository's merges
   */
  merges_url: string;
  /**
   * The API URL of the repository's archive
   */
  archive_url: string;
  /**
   * The API URL of the repository's downloads
   */
  downloads_url: string;
  /**
   * The API URL of the repository's issues
   */
  issues_url: string;
  /**
   * The API URL of the repository's pulls
   */
  pulls_url: string;
  /**
   * The API URL of the repository's milestones
   */
  milestones_url: string;
  /**
   * The API URL of the repository's notifications
   */
  notifications_url: string;
  /**
   * The API URL of the repository's labels
   */
  labels_url: string;
  /**
   * The API URL of the repository's releases
   */
  releases_url: string;
  /**
   * The API URL of the repository's deployments
   */
  deployments_url: string;
  /**
   * The date and time the repository was created
   */
  created_at: string;
  /**
   * The date and time the repository was last updated
   */
  updated_at: string;
  /**
   * The date and time the repository was last pushed to
   */
  pushed_at: string;
  /**
   * The git URL of the repository
   */
  git_url: string;
  /**
   * The SSH URL of the repository
   */
  ssh_url: string;
  /**
   * The clone URL of the repository
   */
  clone_url: string;
  /**
   * The SVN URL of the repository
   */
  svn_url: string;
  /**
   * The homepage of the repository
   */
  homepage?: string | null;
  /**
   * The size of the repository
   */
  size: number;
  /**
   * The number of stars the repository has
   */
  stargazers_count: number;
  /**
   * The number of watchers the repository has
   */
  watchers_count: number;
  /**
   * The programming language used in the repository
   */
  language?: string | null;
  /**
   * Whether the repository has issues enabled
   */
  has_issues: boolean;
  /**
   * Whether the repository has projects enabled
   */
  has_projects: boolean;
  /**
   * Whether the repository has downloads enabled
   */
  has_downloads: boolean;
  /**
   * Whether the repository has a wiki enabled
   */
  has_wiki: boolean;
  /**
   * Whether the repository has pages enabled
   */
  has_pages: boolean;
  /**
   * Whether the repository has discussions enabled
   */
  has_discussions: boolean;
  /**
   * The number of forks the repository has
   */
  forks_count: number;
  /**
   * The mirror URL of the repository
   */
  mirror_url?: string | null;
  /**
   * Whether the repository is archived
   */
  archived: boolean;
  /**
   * Whether the repository is disabled
   */
  disabled: boolean;
  /**
   * The number of open issues the repository has
   */
  open_issues_count: number;
  /**
   * The license used in the repository
   */
  license?: string | null;
  /**
   * Whether the repository allows forking
   */
  allow_forking: boolean;
  /**
   * Whether the repository is a template
   */
  is_template: boolean;
  /**
   * Whether web commit signoff is required
   */
  web_commit_signoff_required: boolean;
  /**
   * A list of topics associated with the repository
   */
  topics?: string[];
  /**
   * The visibility of the repository
   */
  visibility: string;
  /**
   * The number of forks the repository has
   */
  forks: number;
  /**
   * The number of open issues the repository has
   */
  open_issues: number;
  /**
   * The number of watchers the repository has
   */
  watchers: number;
  /**
   * The default branch of the repository
   */
  default_branch: string;
  /**
   * The temporary clone token of the repository
   */
  temp_clone_token?: string | null;
  /**
   * The network count of the repository
   */
  network_count: number;
  /**
   * The number of subscribers the repository has
   */
  subscribers_count: number;
  /**
   * The URL of the repository
   */
  html_url: string;
  [k: string]: unknown;
}
