import { compileFromFile } from 'json-schema-to-typescript';
import fs from 'fs/promises';
import path from 'path';

async function generateTypes() {
  const schemaDir = 'schemas';
  const outputDir = 'src/types';

  try {
    await fs.mkdir(outputDir, { recursive: true }); 

    const files = await fs.readdir(schemaDir);

    for (const file of files) {
      if (file.endsWith('.schema.json')) {
        const schemaPath = path.join(schemaDir, file);
        const tsFileName = file.replace('.schema.json', '.ts');
        const tsOutputPath = path.join(outputDir, tsFileName);

        console.log(`Compiling ${schemaPath} to ${tsOutputPath}...`);
        const tsContent = await compileFromFile(schemaPath, {
           bannerComment: `/* eslint-disable */\n/**\n* This file was automatically generated by json-schema-to-typescript.\n* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,\n* and run json-schema-to-typescript to regenerate this file.\n*/`
        });
        await fs.writeFile(tsOutputPath, tsContent);
        console.log(`Successfully generated ${tsOutputPath}`);
      }
    }
  } catch (error) {
    console.error('Error generating TypeScript types:', error);
  }
}

generateTypes();